# Site settings
title: Otago Children's Autism Support Group
email: hello@otagokidsautism.org
description: >
  Group of pro-active Dunedin parents who have autistic children, committed
  to helping organise and fundraise for intensive early interventions.
baseurl: "/otagokidsautism" # the subpath of your site, e.g. /blog/
url: "http://aaaidan.github.io/otagokidsautism/" # the base hostname & protocol for your site
twitter_username: otagokidsautism

paginate: 3
paginate_path: "/news/page:num/"

permalink: /:categories/:year/:month/:title.html  

navigation:
- title: Home
  url: /
- title: Therapy
  children:
  - title: Introduction to ABA Therapy
    url: /aba-therapy/
  - title: Our Therapists
    url: /therapists/
  - title: Accreditation and Management
    url: /accreditation/
- title: "Kids & Parents"
  children:
  - title: Diagnosis of Autism
    url: /autism-diagnosis/
  - title: Profiles of Our Children
    url: /children/
  - title: Citations from Parents
    url: /citations/
- title: Funding
  url: /funding/
- title: Contact us
  url: /contact/
- title: Links
  url: /links/

collections:
- therapists

# Build settings
markdown: kramdown
